/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MVsxGeI2CKE
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

import { useState } from 'react';

import { Toggle } from '@/components/ui/toggle';

export function StreamText({ text }) {
  const [showStream, setShowStream] = useState(true);

  return (
    <div className="bg-background text-foreground rounded-lg border border-muted p-6 w-full max-w-md">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold">Text Stream</h2>
        <Toggle onCheckedChange={setShowStream} aria-label="Toggle text stream">
          <span className="sr-only">Toggle text stream</span>
        </Toggle>
      </div>
      <div
        className={`overflow-hidden ${showStream ? 'animate-text-stream' : ''}`}
      >
        <p className="text-muted-foreground">
          {text.split('').map((char, index) => (
            <span
              key={index}
              className={`animate-[text-stream_0.1s_${index * 0.1}s_ease-in-out_forwards]`}
            >
              {char}
            </span>
          ))}
        </p>
      </div>
    </div>
  );
}
